### PR TITLE
Feature: editor controls hints

### PR DESCRIPTION
**Pull request by SIGSTACKFAULT**
image

### CODE REVIEW

**Comment by 0111narwhalz** [comment]
This looks to be strictly a text label. With no way to track to changes during development nor a later settings menu, it would seem to just be more effort to maintain.

I do recognize the need, though. I invite you to work out a way to provide that functionality. Otherwise I'll probably hit it when I'm done with shaft power phase two, as part of a pass over the editor to improve usability.

**Comment by SIGSTACKFAULT** [comment]
It's *meant* to be temporary. of course that means it'll probably stay there forever.

**Comment by SIGSTACKFAULT** [comment]
asdfasdfasdf webhook test

**Comment by SIGSTACKFAULT** [comment]
it certainly took me a bit to figure out the controls so i just figured writing them down would be a good idea. obviously Eventually:tm: there would be proper control hints like Space Engineers for example

**Comment by 0111narwhalz** [comment]
Unless you can guarantee that the hinting will accurately reflect what the game will actually do, I don't want ingame hints.

**Comment by SIGSTACKFAULT** [comment]
A whole control scheme management system is definitely premature optimization right now.

**Pull request closed without merging**
